apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkcredentials
spec:
  selector:
    matchLabels:
      app: checkcredentials
      component: api
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: checkcredentials
        component: api
    spec:
      containers:
      - name: api
        image: docker.ausdertechnik.de/uitsmijter/examples/checkcredentials:latest
        envFrom: # ENV FROM PHP App
          - secretRef:
              name: env
        env:
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          value: "mysql://$(DB_USERNAME):$(DB_PASSWORD)@$(DB_HOST):3306/$(DB_DATABASE)"

        livenessProbe:
          httpGet:
            path: /
            port: 3000
        readinessProbe:
          tcpSocket:
            port: 3000

        resources:
          requests:
            memory: "32Mi"
            cpu: "0.1"
          limits:
            memory: "256Mi"
            cpu: "1"

      imagePullSecrets:
        - name: gitlab-auth
